apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
    
spec:
  replicas: <count>
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: 'approle'
          vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
          #avp.kubernetes.io/path: "internal/data/database/config"
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx

