apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
  labels:
    app: nginx
  name: nginx
    
spec:
  replicas: {{ .Data.data.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      serviceAccountName: internal-app
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx

